language: android

notifications:
  email: true

sudo: false


jdk:
  - oraclejdk8


env:
  global:
    - BUILD_TOOLS_VERSION=23.0.3
    - COMPILE_SDK_VERSION=23
  matrix:
    - ANDROID_TARGET_VERSION=23


android:
  components:
    - platform-tools
    - tools

    - build-tools-$BUILD_TOOLS_VERSION

    - android-$COMPILE_SDK_VERSION

    - extra-android-m2repository


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean build
  # quick way to check that Fenum checking works
  # if Fenum checker didn't report anything, grep returns non-zero value and build fails
  - ./gradlew clean checkFenumsDebug 2>&1 | grep "incompatible types in argument"
  - ./gradlew clean checkFenumsRelease 2>&1 | grep "incompatible types in argument"
